# Generated by Django 5.0.3 on 2024-04-15 21:53

import django.core.validators
import django.db.models.deletion
import reservation.config
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(verbose_name='Номер стола')),
                ('place_count', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(10)], verbose_name='Количество мест')),
            ],
            options={
                'verbose_name': 'Стол',
                'verbose_name_plural': 'Столы',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_time', models.DateTimeField(verbose_name='Дата и время')),
                ('duration', models.DurationField(verbose_name='Продолжительность(секунды)')),
                ('client_info', models.CharField(max_length=100, validators=[reservation.config.validate_contact_info], verbose_name='Контактная информация')),
                ('table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservation.table', verbose_name='Стол')),
            ],
            options={
                'verbose_name': 'Бронь',
                'verbose_name_plural': 'Брони',
            },
        ),
    ]
